language: java
jdk:
  - oraclejdk8
install: true
script:
  - ./gradlew :antlr-kotlin-runtime-jvm:test
  - ./gradlew :antlr-kotlin-runtime-js:test
  - ./gradlew install
  - cd antlr-kotlin-runtime-examples-jvm && ../gradlew compileKotlin
  